{% set version = "2.0.3" %}

package:
  name: mss
  version: {{ version }}

source:
  url: https://github.com/Open-MSS/MSS/archive/{{ version }}.tar.gz
  sha256: c2193996f8a2b93164f9c9cbb7edc5893cfc000ba82fe244239b7bf3cab689ef
  patches:
    # start without environment by a application menu needs a PROJ_LIB env too
    - mss_pyui_set_proj_lib_data_dir.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # [not win]
  entry_points:
    - mss = mslib.msui.mss_pyui:main
    - mswms = mslib.mswms.mswms:main
    - mswms_demodata = mslib.mswms.demodata:main
    - mscolab = mslib.mscolab.mscolab:main
    - mss_retriever = mslib.retriever:main

requirements:
  host:
    - python
    - pip
    - future
    - menuinst  # [win]
  run:
    - python
    - defusedxml
    - menuinst  # [win]
    - basemap  >1.2.1
    - chameleon
    - execnet
    - fastkml
    - isodate
    - lxml
    - netcdf4
    - hdf4
    - pillow
    - pytz
    - pyqt >=5,<6
    - pygeoif
    - qt >=5,<6
    - requests
    - scipy
    - skyfield >=1.12
    - tk
    - owslib <=0.21
    - unicodecsv
    - fs_filepicker
    - cftime >=1.0.1
    - matplotlib >=3.3.2
    - flask
    - flask-httpauth
    - werkzeug
    - flask-socketio >=4.3.1, <5
    - flask-sqlalchemy
    - passlib
    - gitpython
    - git
    - psycopg2
    - PyMySQL >=0.9.3
    - validate_email
    - multidict
    - pint
    - python-socketio >=4.4.0, <5
    - python-engineio >=3.13.2, <4
    - markdown
    - xstatic
    - xstatic-jquery
    - xstatic-bootstrap
    - pyperclip
    - geos <3.9.0
    - sqlalchemy  <1.4.0
    - sqlite  <3.35.1

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mswms_demodata -h
    - mss -h
    - mscolab -h

about:
  summary: A QT application, a OGC web map server, a collaboration server to plan atmospheric research flights.
  home: https://github.com/Open-MSS/MSS
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  description: |
    MSS - Mission Support System

    Documentation:
    * https://mss.rtfd.io
    * http://www.geosci-model-dev.net/5/55/2012/gmd-5-55-2012.pdf

    Software for planning research Aircraft Missions.
    For discussion of the possibilites of the research flights,
    the Mission Support System (MSS) was developed.
    This software helps to review a big amount of metereological and
    model data by viewing the forecasted parameters of interest along possible regions
    of a proposed flight path. Data and possible flight paths can
    be displayed on a hoizontal view (map projection) or on a vertical
    view (along the proposed flight path). Flight paths can be constructed
    and modified on these views. Exchange through a waypoint table is also possible.

extra:
  recipe-maintainers:
    - ReimarBauer
