{% set version = "10.1.0" %}

package:
  name: mss
  version: {{ version }}

source:
  url: https://github.com/Open-MSS/MSS/archive/{{ version }}.tar.gz
  sha256: b04ff67c7394fd42c379ca1979f3c947a6c09b8f28e21de5e2c203c1f8f4037b
  patches:
    # remove execfile
    - remove_execfile.patch

build:
  skip: true  # [py>312]
  number: 3

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython >=0.29,<3.1                  # [build_platform != target_platform]
    - numpy >=2                           # [build_platform != target_platform]
    - pip 
    - setuptools
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy >=2
    - defusedxml
    - basemap >=1.3.3
    - chameleon
    - execnet
    - fastkml >=0.11,<1.0.0
    - shapely >=2.0.0
    - pygeoif <1.0.0
    - isodate
    - lxml
    - netcdf4
    - hdf4
    - pillow
    - pyqt >=5.15.0
    - qt >=5.15.0
    - requests >=2.31.0
    - scipy
    - skyfield >=1.12
    - skyfield-data >=6
    - tk
    - owslib >=0.24
    - unicodecsv
    - fs_filepicker >=0.3.9
    - cftime >=1.0.1
    - matplotlib >=3.5.3
    - itsdangerous
    - pyjwt
    - flask >=2.3.2
    - flask-httpauth
    - flask-mail
    - flask-migrate
    - werkzeug >=2.2.3,<3.0.0
    - flask-socketio >=5.1.0
    - flask-sqlalchemy >=3.0.0
    - flask-cors
    - passlib
    - gitpython
    - git
    - psycopg2
    - pymysql >=0.9.3
    - validate_email
    - multidict
    - pint
    - python-socketio >=5
    - python-engineio >=4
    - markdown
    - xstatic
    - xstatic-jquery
    - xstatic-bootstrap
    - gpxpy >=1.4.2
    - metpy
    - pycountry
    - websocket-client
    - libtiff
    - flask-wtf
    - email_validator
    - keyring
    - dbus-python  # [not win]
    - python-slugify
    - flask-login
    - pysaml2
    - libxmlsec1  # [not win]

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mswms_demodata -h
    - msui -h
    - mscolab -h
    - mssautoplot --help
    - msidp -h  # [not win]

about:
  summary: 'A client/server application developed in the community to collaboratively create flight plans based on model data.'
  home: https://github.com/Open-MSS/MSS
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: LICENSE
  description: |
    MSS - Mission Support System

    Documentation:
    * https://mss.rtfd.io
    * https://gmd.copernicus.org/articles/15/8983/2022/gmd-15-8983-2022.pdf
    * http://www.geosci-model-dev.net/5/55/2012/gmd-5-55-2012.pdf

    Software for planning research Aircraft Missions.
    For discussion of the possibilities of the research flights,
    the Mission Support System (MSS) was developed.
    This software helps to review a big amount of metereological and
    model data by viewing the forecasted parameters of interest along possible regions
    of a proposed flight path. Data and possible flight paths can
    be displayed on a hoizontal view (map projection) or on a vertical
    view (along the proposed flight path). Flight paths can be constructed
    and modified on these views. Exchange through a waypoint table is also possible.

extra:
  recipe-maintainers:
    - ReimarBauer
