{% set version = "1.9.5" %}

package:
  name: mss
  version: {{ version }}

source:
  url: https://bitbucket.org/wxmetvis/mss/get/{{ version }}.tar.gz
  sha256: 4e2f50d5d471339514f2144128be9f0f286a145ff269472311ebe81feae6f655
  patches:
    # start without environment by a application menu needs a PROJ_LIB env too
    - mss_pyui_set_proj_lib_data_dir.patch

build:
  skip: true  # [py<=27 or py>=38]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]
  entry_points:
    - mss = mslib.msui.mss_pyui:main
    - mswms = mslib.mswms.mswms:main
    - mswms_demodata = mslib.mswms.demodata:main
    - mscolab = mslib.mscolab.server:main
    - mscolab_demodata = mslib.mscolab.demodata:main
    - mscolab_add_permissions = mslib.mscolab.add_bulk_permissions:main

requirements:
  host:
    - python
    - pip
    - future
    - menuinst  # [win]
  run:
    - python
    - defusedxml
    - menuinst  # [win]
    - basemap >=1.2.0
    - chameleon
    - execnet
    - isodate
    - lxml
    - netcdf4
    - hdf4
    - pillow >=5,<6
    - pytz
    - pyqt >=5,<6
    - qt >=5,<6
    - requests
    - scipy
    - skyfield >=1.12
    - tk
    - owslib
    - unicodecsv
    - fs_filepicker
    - cftime >=1.0.1
    - matplotlib ==3.0.2
    - proj4 <6
    - flask
    - flask-httpauth
    - werkzeug
    - flask-socketio
    - flask-sqlalchemy
    - passlib
    - gitpython
    - git
    - psycopg2
    - validate_email
    - multidict
    - pint
    - python-socketio >=4.4.0

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mss -h
    - mscolab_demodata -h

about:
  summary: 'A QT application and a OGC web server to plan atmospheric research flights.'
  home: https://bitbucket.org/wxmetvis/mss
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: LICENSE
  description: |
    MSS - Mission Support System

    Documentation:
    * https://mss.rtfd.io
    * http://www.geosci-model-dev.net/5/55/2012/gmd-5-55-2012.pdf

    Software for planning research Aircraft Missions.
    For discussion of the possibilites of the research flights,
    the Mission Support System (MSS) was developed.
    This software helps to review a big amount of metereological and
    model data by viewing the forecasted parameters of interest along possible regions
    of a proposed flight path. Data and possible flight paths can
    be displayed on a hoizontal view (map projection) or on a vertical
    view (along the proposed flight path). Flight paths can be constructed
    and modified on these views. Exchange through a waypoint table is also possible.

extra:
  recipe-maintainers:
    - ReimarBauer
