{% set version = load_setup_py_data().version %}

package:
  name: mss
  version: {{ version }}

source:
  fn: mss-{{ version }}.tar.gz
  url: https://bitbucket.org/wxmetvis/mss/get/{{ version }}.tar.gz
  sha256: 982e70d58e8871bf8de586806c3e200f922e39e0c905128572a9af161bfa21f0

build:
  number: 0
  skip: True  # [py3k]
  entry_points:
    - mss = mslib.msui.mss_pyui:main
    - mswms = mslib.mswms.mswms:main
    - demodata = mslib.mswms.demodata:main

requirements:
  build:
    - python
    - setuptools
    - menuinst [win]
  run:
    - python
    - menuinst [win]
    - basemap 1.0.7
    - chameleon
    - execnet
    - lxml
    - netcdf4
    - hdf4 4.2.12
    - paste
    - pillow
    - python-dateutil
    - pytz
    - pyqt
    - requests
    - scipy
    - six
    - tk 8.5.*
    - pykml

test:
  imports:
    - mslib
  commands:
    - mswms -h
    - mss -h

about:
  summary: 'A web service based tool to plan atmospheric research flights.'
  home: https://bitbucket.org/wxmetvis/mss
  license: Apache 2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ReimarBauer
