appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: T+b5BDg9VtqpII+uQz/k3Ni1oakcBBPEOrfAkb5iyphrOEr1Jo3MBVqH7JjgeFaNRVluVv+L694EYGym+rhy2ACWT8Rz0zmL2H3Uf9YMmaq6heXASAgRQ06HnSFdra4SrMQ7ZO1msz5nPVNvAaLBpNc0Xiqwf26Qq5SZiqsWPndsWIUu46DW1lUJ8TVpiqLy4fwtvnbCw7UOOhz4JoT6K6WhBgPyYl4fyOtJXQB7JuVttdRjbiAhHchir9cMRFRkV3uRD+pNlH4CaCQ7xAIoi00jVhVNBf/gXETdFEL2m6AtrKuGh0Bja579fKXjnd2O62QJ7eY9Y2YTZkdBnBEGPyvyB0C8cMDSTVsJR2VY8eAblXIUCyTfZAWKJk/dspO1HFL5io87nLd/i7T1z+dJLewERQ99yoKTPnMm1iutcvIUNQo6E78T6ca6AsvMyJfUltxqqOaHo7phdKp8UvvVz6vXffYGvW31K4TFUAE2b5U2IgHjSXk81uWfcV5Su7qDWeAPTwYeNsVVFhekI2aKU3SUyUWJL6xlxOwGeqD7cKvCxOYAU4BzC03gKSVnDoxQAaFeiix2mEtFT7jgXqEPDGR4nvv5japdvNyC9SfhDqHf7+iyTryn70yuKV9CHe9NEMNmtt92CDqTX+H9KZPWut6IwXKld77QdNOT5Ep/Afc=}
provider:
  win: azure
conda_forge_output_validation: true
